apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: notification_db
  GRPC_PORT: "50054"
  HTTP_PORT: "8084"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: todo-notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50054
          name: grpc
        - containerPort: 8084
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: DB_NAME
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: GRPC_PORT
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: notification-service-config
              key: HTTP_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 50054
    targetPort: 50054
    name: grpc
  - port: 8084
    targetPort: 8084
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-http
spec:
  selector:
    app: notification-service
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
  type: NodePort

