apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: task_db
  GRPC_PORT: "50053"
  HTTP_PORT: "8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: todo-task-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50053
          name: grpc
        - containerPort: 8083
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: DB_NAME
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: GRPC_PORT
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: task-service-config
              key: HTTP_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
  - port: 50053
    targetPort: 50053
    name: grpc
  - port: 8083
    targetPort: 8083
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: task-service-http
spec:
  selector:
    app: task-service
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
  type: NodePort

